# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "bHVRZCtgbsfTdF8A3F+3RdSSo+xJ1Kxh03S32m9kgKqejT+gP6K8t0MUJhAC8k99z5FBAnT81X0VyOdPDpfL0nPuFjFzQKx5g9yF0DHNEJSovPisiPWE7QKv/go2RdCVRoiwtrn0rSylzST0Rmh/eNZdUDK/WUYHyXW70jsvYFkRdq0x0A0mnbfF1sdc3waBMkfeHrOktUbj7JAJem7681ftqmXCKpkE1AQ175JQCYkEnz1cjLlFDDO6RRTkc9mUHg862gqPBNjnvk1mMdH3JETgUOTjXxH+RKdEWpxANOLTgCvED6qhSvNlEoH8C356im9IfVLbXH8YMugh/QkN491BDEuucZj5NUBsSvgGB9W6b1tOpO+OBQhtTqNiDx4+Eg9WTzqylPlSMqPUruWubPH3gX4Iu2Wu4S/h9soTey1WZ8vD8ycx8EWMYoMJSFD/ijfJa5FGlc7Q6g99l9dlUsNkmb3QAoa9+FFFeO2WXbbYOy2W5uENRlsyHTtjO8DNLHKf9pDYhVr8x5v7phIch1DKRWSgzta60+A2LdrX2FS8W8Awyj07Bfdb3CFft1yZ041fF395dVPly+KS4B7efrZIz5EBQ4yywGYQpFKauJLfJx/sN6D8GtjZ+6NYyNnY6EC8lvcplm1RJg0qviQSy8w/V86fGst3B2C+DN8gLPA="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylistgermany" output
  - flrender -i easylistgermany=. easylistgermany.template output/easylistgermany.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

