# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "yZVA/8H3BCldTHzJvne26ch69SsigGtuk6KUPQbIo/Zl11KI/17sjDbJbmhxqJ1OlKuX2udrOL63FCuCB8xiTy9KvrXZpLJCvAIpYhwiy0I0gdyTEW/oAplvDCKLnFctkupWxpTsk740geswJVp4A6DBfIp0hL5VltO2N/7FAZ1Rej6vIoE+7XZ7X+GYmGtO/sUt/AdLsfO8AvFx1TNu0rvbrUkVv6bOyx13d5/RLibIM809AkqH/p1KLQwt6WxwsqLtk1TsuAiA3Ot+xhQ4gUeyBYzZds8gYlK0mRnHIc8kBKuxj/9MWHQv9/uLwklkTF73BZ7owRNvzaqqYsBmYTf+93c5tSNJCXeouGJtW7ciPsim9II2mnnn8yiImOYehW5U3vbLduHiqh9VMImjd8WanAeUZY1a+fE8p3mnXv4+8TxOSIhlDovH7lH974MMawUTxrXAPsiGXQh90o/iOX9y39zX0Er+394Dwd0DB8OWj7gH60bCWExk55yaM6eR1VooK320yba5/zwHRcWvozTIRFv+1i2HhpLcZ7uGE8eLbz1MfBVIT3oKe+N7JDlLUrbQQY0rRY8ePJVBWQn1Y8Zkl+eNLRhgZaoppE0xYm3L7QUBnvSt88uIj+XsyYEKbfO3RsGvp6Ik8qtWEhDSswXJrxPuzDDImw2BmHgLt7I="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylistgermany" output
  - flrender -i easylistgermany=. easylistgermany.template output/easylistgermany.txt
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

